#!/usr/bin/env bash
set -euo pipefail

mode="${GAME_MODE:-renewal}"
packetver="${PACKETVER:-20211103}"
renewal="${RENEWAL:-true}"
db_host="${MYSQL_HOST:-db}"
db_name="${GAME_DB_NAME:-ragnarok}"
db_user="${MYSQL_USER:-ragnarok}"
db_password="${MYSQL_PASSWORD:-ragnarok}"
db_root_password="${MYSQL_ROOT_PASSWORD:-ragnarok}"
server_host="${GAME_HOST:-serve}"
bind_ip="${RATHENA_BIND_IP:-serve}"

case "$mode" in
	renewal)
		packetver="${PACKETVER:-20211103}"
		renewal=true
		;;
	pre-renewal|prerenewal)
		mode=pre-renewal
		packetver="${PACKETVER:-20141022}"
		renewal=false
		;;
	*)
		echo "Unsupported GAME_MODE: $mode (use renewal or pre-renewal)" >&2
		exit 1
		;;
esac

case "$packetver" in
	20141022)
		mode=pre-renewal
		renewal=false
		;;
	20211103)
		mode=renewal
		renewal=true
		;;
	20250122)
		mode=renewal
		renewal=true
		;;
	*)
		echo "Unsupported PACKETVER: $packetver (supported: 20141022, 20211103, 20250122)" >&2
		exit 1
		;;
esac

replace_conf() {
	local file="$1"
	local key="$2"
	local value="$3"
	sed -i -E "s|^[[:space:]]*(//[[:space:]]*)?${key}:[[:space:]].*$|${key}: ${value}|" "$file"
}

cd /rathena

replace_conf conf/inter_athena.conf login_server_ip "$db_host"
replace_conf conf/inter_athena.conf ipban_db_ip "$db_host"
replace_conf conf/inter_athena.conf char_server_ip "$db_host"
replace_conf conf/inter_athena.conf map_server_ip "$db_host"
replace_conf conf/inter_athena.conf web_server_ip "$db_host"
replace_conf conf/inter_athena.conf log_db_ip "$db_host"
replace_conf conf/char_athena.conf login_ip "$server_host"
replace_conf conf/char_athena.conf bind_ip "$bind_ip"
replace_conf conf/char_athena.conf char_ip "$server_host"
replace_conf conf/map_athena.conf char_ip "$server_host"
replace_conf conf/map_athena.conf bind_ip "$bind_ip"
replace_conf conf/map_athena.conf map_ip "$server_host"
replace_conf conf/login_athena.conf bind_ip "$bind_ip"

# ==========================================================
# NUOVA LOGICA: Creazione dinamica di defines_pre.hpp
# ==========================================================

if [ "$mode" = "renewal" ]; then
    echo "Generazione src/custom/defines_pre.hpp per server Renewal..."
    cat > src/custom/defines_pre.hpp <<EOF
// Generated by Docker Compose. Do not edit manually.
#ifndef CONFIG_CUSTOM_DEFINES_PRE_HPP
#define CONFIG_CUSTOM_DEFINES_PRE_HPP
#define ROBROWSER_PACKETVER ${packetver}
#define ROBROWSER_RENEWAL $([ "$renewal" = "true" ] && echo 1 || echo 0)
#endif
EOF
else # pre-renewal o prerenewal
    echo "Generazione src/custom/defines_pre.hpp per server Pre-Renewal..."
    cat > src/custom/defines_pre.hpp <<EOF
// Generated by Docker Compose. Do not edit manually.
#ifndef CONFIG_CUSTOM_DEFINES_PRE_HPP
#define CONFIG_CUSTOM_DEFINES_PRE_HPP
#define PACKET_OBFUSCATION_KEY1 0x290551EA
#define PACKET_OBFUSCATION_KEY2 0x2B952C75
#define PACKET_OBFUSCATION_KEY3 0x2D67669B
#endif
EOF
fi

# ==========================================================

PACKETVER="$packetver"
export RENEWAL="$renewal"
export PACKETVER
export MYSQL_HOST="$db_host"
export MYSQL_DATABASE="$db_name"
export MYSQL_USER="$db_user"
export MYSQL_PASSWORD="$db_password"
export MYSQL_ROOT_PASSWORD="$db_root_password"

until mysql -h"$db_host" -uroot -p"$db_root_password" -e "SELECT 1" > /dev/null 2>&1; do
	echo "Waiting for database to be ready..."
	sleep 2
done


./configure --enable-packetver="$packetver"
make clean
make server

/bin/bash /pre-import.sh
/bin/bash /20-fluxcp-schemas.sh
./athena-start start
exec tail -f /dev/null
