map $http_referer $renewal_request {
    default 0;
    "~*/renewal/" 1;
}

server {
    listen 80;
    index index.php index.html;
    root /var/www/roBrowser;
    
    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_pass app:9000;
    }

    location /client/ {
        try_files $uri $uri/ /client/index.php?request=$uri&$query_string;
    }

    location /renewal/ {
        proxy_pass http://renewal:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /@vite/ {
        proxy_pass http://renewal:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /src/ {
        if ($renewal_request) {
            return 418;
        }
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /node_modules/ {
        proxy_pass http://renewal:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    error_page 418 = @renewal_src;

    location @renewal_src {
        proxy_pass http://renewal:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }


    location / {
        return 302 /renewal/;
    }
}
